/**
 * Generate + fund the FLOW role wallets on the Tempo testnet and write a
 * ready-to-run .env at the repo root. Run: `pnpm wallets:setup`.
 *
 * ⚠️ TESTNET ONLY. Funds each wallet via the `tempo_fundAddress` faucet RPC.
 * If .env already exists it is NOT overwritten — the script prints the lines
 * instead so you can merge manually.
 */

import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { generatePrivateKey } from "viem/accounts";
import { createWallet, fundWallet } from "../wallet.js";
import {
  TEMPO_RPC_URL,
  TEMPO_CHAIN_ID,
  FLOW_CURRENCY,
  ESCROW_CONTRACT,
} from "../currency.js";

const ROLES = ["VIEWER", "CREATOR", "ADVERTISER"] as const;
const FUND_AMOUNT = "5"; // only used by the master-transfer fallback

const here = dirname(fileURLToPath(import.meta.url));
const envPath = resolve(here, "../../../.env"); // repo root

async function main() {
  console.log("\n=== FLOW wallet setup (Tempo TESTNET) ===\n");
  const keys: Record<string, string> = {};

  for (const role of ROLES) {
    const w = createWallet();
    let fundResult: string | null = null;
    try {
      fundResult = await fundWallet(w.address, FUND_AMOUNT);
    } catch (err) {
      console.error(`  ! funding failed for ${role}:`, (err as Error).message);
    }
    console.log(`${role}: ${w.address}`);
    console.log(`  funding: ${fundResult ?? "SKIPPED"}`);
    keys[`${role}_PRIVATE_KEY`] = w.privateKey;
  }

  const env = [
    "# FLOW .env — Tempo TESTNET ONLY. Generated by `pnpm wallets:setup`.",
    `TEMPO_RPC_URL=${TEMPO_RPC_URL}`,
    `TEMPO_CHAIN_ID=${TEMPO_CHAIN_ID}`,
    `FLOW_CURRENCY=${FLOW_CURRENCY}`,
    `TEMPO_ESCROW_CONTRACT=${ESCROW_CONTRACT}`,
    `MPP_SECRET_KEY=${generatePrivateKey()}`,
    ...Object.entries(keys).map(([k, v]) => `${k}=${v}`),
    "SERVER_PORT=3000",
    "SERVER_URL=http://localhost:3000",
    "WEB_PORT=5173",
    "PRICE_CREATOR_PER_SEC=0.002",
    "PRICE_ATTENTION_PER_SEC=0.004",
    "",
    "# --- Web app (Vite, browser). TESTNET ONLY — key is bundled client-side. ---",
    `VITE_VIEWER_PRIVATE_KEY=${keys["VIEWER_PRIVATE_KEY"]}`,
    "VITE_SERVER_URL=http://localhost:3000",
    "",
  ].join("\n");

  if (existsSync(envPath)) {
    console.log(`\n.env already exists at ${envPath} — NOT overwriting.`);
    console.log("--- merge these lines manually ---\n" + env);
  } else {
    writeFileSync(envPath, env, "utf8");
    console.log(`\nWrote ${envPath}`);
  }
  console.log("\nDone. Never commit .env / these keys.\n");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
